baseurl = "https://ravi13dayyala.github.io/testing-blog-site/"
languageCode = "en-us"
theme = "terminal"
pagination.pagerSize = 5

[markup.goldmark.renderer]
  unsafe = true

[params]
  contentTypeName = "posts"
  showMenuItems = 4
  fullWidthTheme = false
  centerTheme = false

[languages]
  [languages.en]
    title = "Dayyala Ravi"
    subtitle = "Welcome to my first site :)"
    keywords = ""
    copyright = ""
    showmore = "show more" 
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Dayyala Ravi"
      logoHomeLink = "/"

    [languages.en.menu]
      
      [[languages.en.menu.main]]
        identifier = "home"
        name = "Home"
        url = "/"
        
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      
      [[languages.en.menu.main]]
        identifier = "blogs"
        name = "Blogs"
        url = "/posts"

      [[languages.en.menu.main]]
        identifier = "resources"
        name = "Resources"
        url = "/resources"



