baseurl = "https://silent-resistor.github.io/"
languageCode = "en-us"
theme = "terminal"
pagination.pagerSize = 5

[markup.goldmark.renderer]
  unsafe = true

[params]
  contentTypeName = "posts"
  showMenuItems = 4
  fullWidthTheme = false
  centerTheme = true
  customCSS = ["css/custom.css"]
  favicon = "favicon.png"

[languages]
  [languages.en]
    title = "Silent Resistor"
    copyright = ""


    [languages.en.params.logo]
      logoText = "Silent Resistor"
      logoHomeLink = "/"

    [languages.en.menu]
      
      [[languages.en.menu.main]]
        identifier = "home"
        name = "Home"
        url = "/"
        weight = 1
        
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
        weight = 2
      
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts"
        weight = 3 

      [[languages.en.menu.main]]
        identifier = "resources"
        name = "Resources"
        url = "/resources"
        weight = 4



